#include "ZoneVocabulary.h"

#include <stdlib.h>

namespace {
const char* wordFor(uint16_t index) {
    switch (index) {
        case 0x002: return "abort";
        case 0x003: return "ac";
        case 0x004: return "access";
        case 0x005: return "alarm";
        case 0x006: return "and";
        case 0x007: return "announcement";
        case 0x008: return "area";
        case 0x009: return "arm";
        case 0x00A: return "armed";
        case 0x00B: return "arming";
        case 0x00C: return "at";
        case 0x00D: return "attic";
        case 0x00E: return "audio";
        case 0x00F: return "auto";
        case 0x010: return "automation";
        case 0x011: return "auxiliary";
        case 0x012: return "away";
        case 0x013: return "babys";
        case 0x014: return "back";
        case 0x015: return "basement";
        case 0x016: return "bathroom";
        case 0x017: return "battery";
        case 0x018: return "bedroom";
        case 0x019: return "bonus";
        case 0x01A: return "break";
        case 0x01B: return "button";
        case 0x01C: return "bypass";
        case 0x01D: return "bypassed";
        case 0x01E: return "cabinet";
        case 0x01F: return "cancel";
        case 0x020: return "carbon_monoxide";
        case 0x021: return "cellar";
        case 0x022: return "cellular";
        case 0x023: return "cell_radio";
        case 0x024: return "center";
        case 0x025: return "check";
        case 0x026: return "chest";
        case 0x027: return "childrens";
        case 0x028: return "chime";
        case 0x029: return "closet";
        case 0x02A: return "code";
        case 0x02B: return "communications";
        case 0x02C: return "computer";
        case 0x02D: return "control";
        case 0x02E: return "cool";
        case 0x02F: return "crawl";
        case 0x030: return "current";
        case 0x031: return "day";
        case 0x032: return "degrees";
        case 0x033: return "den";
        case 0x034: return "detector";
        case 0x035: return "dim";
        case 0x036: return "dining";
        case 0x037: return "disarm";
        case 0x038: return "disarmed";
        case 0x039: return "dock";
        case 0x03A: return "door";
        case 0x03B: return "downstairs";
        case 0x03C: return "driveway";
        case 0x03D: return "east";
        case 0x03E: return "eight";
        case 0x03F: return "eighteen";
        case 0x040: return "eighty";
        case 0x041: return "electric";
        case 0x042: return "eleven";
        case 0x043: return "emergency";
        case 0x044: return "enter";
        case 0x045: return "entrance";
        case 0x046: return "entry";
        case 0x047: return "error";
        case 0x048: return "exercise";
        case 0x049: return "exit";
        case 0x04A: return "exit_now";
        case 0x04B: return "exterior";
        case 0x04C: return "external";
        case 0x04D: return "failure";
        case 0x04E: return "family";
        case 0x04F: return "fan";
        case 0x050: return "fifteen";
        case 0x051: return "fifty";
        case 0x052: return "fire";
        case 0x053: return "fire_alert";
        case 0x054: return "fire_detector";
        case 0x055: return "first";
        case 0x056: return "five";
        case 0x057: return "flood";
        case 0x058: return "floor";
        case 0x059: return "fluid";
        case 0x05A: return "foil";
        case 0x05B: return "for";
        case 0x05C: return "forty";
        case 0x05D: return "four";
        case 0x05E: return "fourteen";
        case 0x05F: return "fourth";
        case 0x060: return "freeze";
        case 0x061: return "freezer";
        case 0x062: return "front";
        case 0x063: return "furnace";
        case 0x064: return "game";
        case 0x065: return "garage";
        case 0x066: return "gas";
        case 0x067: return "glass";
        case 0x068: return "glass_break";
        case 0x069: return "guest";
        case 0x06A: return "gun";
        case 0x06B: return "hall";
        case 0x06C: return "hallway";
        case 0x06D: return "hanging";
        case 0x06E: return "hang_up";
        case 0x06F: return "heat";
        case 0x070: return "high";
        case 0x071: return "home";
        case 0x072: return "house";
        case 0x073: return "ice";
        case 0x074: return "inside";
        case 0x075: return "instant";
        case 0x076: return "interior";
        case 0x077: return "intrusion";
        case 0x078: return "is";
        case 0x079: return "key";
        case 0x07A: return "keyfob";
        case 0x07B: return "keypad";
        case 0x07C: return "kids";
        case 0x07D: return "kitchen";
        case 0x07E: return "laundry";
        case 0x07F: return "left";
        case 0x080: return "level";
        case 0x081: return "library";
        case 0x082: return "light";
        case 0x083: return "lights";
        case 0x084: return "liquor";
        case 0x085: return "living";
        case 0x086: return "loading";
        case 0x087: return "lock";
        case 0x088: return "loft";
        case 0x089: return "low";
        case 0x08A: return "main";
        case 0x08B: return "maintenance";
        case 0x08C: return "master";
        case 0x08D: return "medical";
        case 0x08E: return "medicine";
        case 0x08F: return "menu";
        case 0x090: return "middle";
        case 0x091: return "monitor";
        case 0x092: return "motion";
        case 0x093: return "motion_detector";
        case 0x094: return "mud";
        case 0x095: return "nine";
        case 0x096: return "nineteen";
        case 0x097: return "ninety";
        case 0x098: return "north";
        case 0x099: return "not";
        case 0x09A: return "not_ready";
        case 0x09B: return "no_delay";
        case 0x09C: return "no_entry_delay";
        case 0x09D: return "nursery";
        case 0x09E: return "off";
        case 0x09F: return "office";
        case 0x0A0: return "on";
        case 0x0A1: return "one";
        case 0x0A2: return "one_hundred";
        case 0x0A3: return "output";
        case 0x0A4: return "outside";
        case 0x0A5: return "panel";
        case 0x0A6: return "panic";
        case 0x0A7: return "pantry";
        case 0x0A8: return "patio";
        case 0x0A9: return "perimeter";
        case 0x0AA: return "phone_line";
        case 0x0AB: return "play";
        case 0x0AC: return "police";
        case 0x0AD: return "pool";
        case 0x0AE: return "pound";
        case 0x0AF: return "power";
        case 0x0B0: return "press";
        case 0x0B1: return "previous";
        case 0x0B2: return "pump";
        case 0x0B3: return "radio";
        case 0x0B4: return "ready";
        case 0x0B5: return "rear";
        case 0x0B6: return "relay";
        case 0x0B7: return "remote";
        case 0x0B8: return "repeat";
        case 0x0B9: return "rf_jam";
        case 0x0BA: return "right";
        case 0x0BB: return "room";
        case 0x0BC: return "safe";
        case 0x0BD: return "second";
        case 0x0BE: return "security";
        case 0x0BF: return "sensor";
        case 0x0C0: return "sensors";
        case 0x0C1: return "session";
        case 0x0C2: return "set";
        case 0x0C3: return "seven";
        case 0x0C4: return "seventeen";
        case 0x0C5: return "seventy";
        case 0x0C6: return "shed";
        case 0x0C7: return "shop";
        case 0x0C8: return "side";
        case 0x0C9: return "silent";
        case 0x0CA: return "siren";
        case 0x0CB: return "six";
        case 0x0CC: return "sixteen";
        case 0x0CD: return "sixty";
        case 0x0CE: return "skylight";
        case 0x0CF: return "sliding";
        case 0x0D0: return "smoke";
        case 0x0D1: return "sounder";
        case 0x0D2: return "south";
        case 0x0D3: return "space";
        case 0x0D4: return "spare";
        case 0x0D5: return "stairs";
        case 0x0D6: return "star";
        case 0x0D7: return "status";
        case 0x0D8: return "stay";
        case 0x0D9: return "stop";
        case 0x0DA: return "storage";
        case 0x0DB: return "study";
        case 0x0DC: return "sump";
        case 0x0DD: return "supervision";
        case 0x0DE: return "system";
        case 0x0DF: return "tamper";
        case 0x0E0: return "temperature";
        case 0x0E1: return "ten";
        case 0x0E2: return "terminated";
        case 0x0E3: return "thermostat";
        case 0x0E4: return "third";
        case 0x0E5: return "thirteen";
        case 0x0E6: return "thirty";
        case 0x0E7: return "three";
        case 0x0E8: return "to";
        case 0x0E9: return "tool";
        case 0x0EA: return "transmitted";
        case 0x0EB: return "transmitter";
        case 0x0EC: return "trouble";
        case 0x0ED: return "turn";
        case 0x0EE: return "twelve";
        case 0x0EF: return "twenty";
        case 0x0F0: return "two";
        case 0x0F1: return "unlock";
        case 0x0F2: return "upper";
        case 0x0F3: return "upstairs";
        case 0x0F4: return "user";
        case 0x0F5: return "utility";
        case 0x0F6: return "valve";
        case 0x0F7: return "voice";
        case 0x0F8: return "wall";
        case 0x0F9: return "water";
        case 0x0FA: return "west";
        case 0x0FB: return "window";
        case 0x0FC: return "wireless";
        case 0x0FD: return "yard";
        case 0x0FE: return "zero";
        case 0x0FF: return "zone";
        case 0x12B: return "balcony";
        case 0x12C: return "courtyard";
        case 0x12D: return "deck";
        case 0x12E: return "detached";
        case 0x12F: return "overhead";
        case 0x130: return "refrigerator";
        case 0x131: return "service";
        case 0x132: return "sunroom";
        case 0x133: return "warehouse";
        case 0x134: return "gate";
        case 0x135: return "apartment";
        case 0x136: return "foyer";
        case 0x137: return "tv";
        case 0x138: return "video";
        case 0x139: return "porch";
        case 0x13A: return "corner";
        case 0x13B: return "bell";
        case 0x13C: return "boys";
        case 0x13D: return "camera";
        case 0x13E: return "cave";
        case 0x13F: return "daughters";
        case 0x140: return "doorbell";
        case 0x141: return "girls";
        case 0x142: return "image";
        case 0x143: return "image_sensor";
        case 0x144: return "man";
        case 0x145: return "sons";
        case 0x146: return "sun";
        case 0x147: return "theater";
        case 0x148: return "wing";
        case 0x149: return "switch";
        default: return nullptr;
    }
}
}  // namespace

namespace ZoneVocabulary {

String decode(const String& descriptor) {
    if (descriptor.length() < 15 || descriptor.length() > 16) return String();
    char* end = nullptr;
    uint64_t packed = strtoull(descriptor.c_str(), &end, 16);
    if (end == descriptor.c_str() || *end != '\0') return String();
    if (descriptor.length() < 16) {
        packed <<= 4 * (16 - descriptor.length());
    }

    String name;
    for (uint8_t word = 0; word < 5; ++word) {
        const uint8_t shift = 64 - 12 * (word + 1);
        const uint16_t index = static_cast<uint16_t>((packed >> shift) & 0xFFF);
        if (index == 0) break;
        const char* vocabulary = wordFor(index);
        if (vocabulary == nullptr) return String();
        String part(vocabulary);
        part.replace('_', ' ');
        if (!name.isEmpty()) name += ' ';
        name += part;
    }
    return name;
}

}  // namespace ZoneVocabulary
